repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: .JuliaFormatter.toml
        args: [--unique]
      - id: mixed-line-ending
        fix: "lf"
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
  - repo: "https://github.com/domluna/JuliaFormatter.jl"
    rev: v1.0.34
    hooks:
      - id: "julia-formatter"
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
